csc:
  hosts:
    koe7:
      hostname: koe7
      ansible_ssh_host: 128.214.254.177
      ansible_port: 22
      ansible_connection: ssh
      ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
  vars:
    infradir: /opt/tyokoe
    appdir: /opt/tyokoe/csc2022
    domain: koe7-dv.csc.fi
    key: "/home/cloud-user/koe7-dv.csc.fi.key"
    certificate: "/home/cloud-user/koe7-dv_csc_fi_cert.cer"
    intermediate_certificate: "/home/cloud-user/koe-dv_csc_fi_interm.cer"
    pem: "{{ infradir }}/ssl.pem"
    postgres:
      application:
        user: csc2022
        password: "katatoninen tietokanta"
        database: csc2022
    developers:
      - name: Jarno Luttinen
        account: jluttinen
      - name: Jermu Mäki
        account: jmaki
      - name: Jouko Johansson
        account: jjohansson
      - name: Mohamid Shaker
        account: mshaker
      - name: Tommi Sahimäki
        account: tsahimaki
      - name: Zoltan Varga
        account: zvarga
      - name: Teijo Kokko
        account: tkokko
